name: Build libflac from a tarball
on: [push, pull_request]
jobs:
  libflac:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          release: false
      - name: Install Pd
        run: |
          wget -q https://ftp.osuosl.org/pub/xiph/releases/flac/flac-1.3.3.tar.xz
          tar xvf flac-1.3.3.tar.xz
      - name: help
        working-directory: flac-1.3.3
        run: |
          ./configure --help
      - name: build
        working-directory: flac-1.3.3
        run: |
          ./configure
          make
          make install
